src/FluentResults/FluentResults.csproj
Hi @altmann, thanks for the package! 
I've added a netstandard 2.0 target to create a smaller package dependency graph. All platforms supporting .NET Standard 2.0 will use the netstandard2.0 target and benefit from having a smaller package graph while older platforms will still work and fall back to using the netstandard1.1 target.
Please see https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting#net-standard for more details if required.
I didn't increase your `<PackageVersion>` because I wasn't sure if you felt this would be a minor or patch version increase. If you let me know what version you would like, I can update my PR.
=> Include a netstandard2.0 target

src/FluentResults.Extensions.FluentAssertions/ResultAssertions.cs
Previously with just `AndConstraint`, to chain anything more complex you had to route back through the `Subject` property, e.g.,
```result.Should().BeSuccess().And.Subject.Value.Should().BeEquivalentTo(expectedValues)```
The `AndWhichContraint` simplifies this slightly as it gives direct access back to the original subject through the `Which` property.  It allows the above statement to be simplified slightly to:
```result.Should().BeSuccess().Which.Value.Should().BeEquivalentTo(expectedValues)```
It's a relatively minor change, but it allows the sentence to flow nicer.
=> Returning AndWhichConstraint from FluentAssertion extensions

src/FluentResults.Test/ResultWithValueTests.cs, src/FluentResults.Test/ResultWithoutValueTests.cs, src/FluentResults/Results/Result.cs
Changes described in #86.  
Additional parameter added to ToResult to allow specifying the value to use when transforming a result.  Defaulted to `default` to retain the existing functionality and API.
This method only applies to the non-generic `Result` type.  If applied to the generic `Result<T>` type, it would be ignoring the existing value which seems like bad practice.
Also corrected the name of the `ToResult_ToAntotherValueTypeWithOkResultAndConverter_ReturnFailedResult` test as it was incorrectly named based on the assert condition.
=> Accepting of a TNewValue for ToResult

src/FluentResults/Results/Result.cs, src/FluentResults/Results/ResultBase.cs
Hey there,
I've integrated your library into my project and figured out that `Result` classes don't support covariance and in some cases, it's at pains to use generics due to having a lot of explicit conversions. 
Here is a small example:
```csharp
interface IContract<T>
{
Result<T> GetValueExplicitly();
IResult<T> GetValueImplicitly();
}
abstract class BaseValue { } 
interface IContractExecutor : IContract<BaseValue> {}
class ContractExecutor<T> : IContractExecutor where T: BaseValue, new()
{
public Result<BaseValue> GetValueExplicitly() 
{ 
return Result.Ok((BaseValue) new T()); 
}
public IResult<BaseValue> GetValueImplicitly() 
{ 
return Result.Ok(new T());
}
}
```
Hope you find it useful and thanks for the cool Result implementation!
=> Added covariant interfaces for Result classes

README.md, src/FluentResults.Test/Mocks/LoggingMock.cs, src/FluentResults.Test/ResultLoggingTests.cs, src/FluentResults/Logging/DefaultLogger.cs, src/FluentResults/Logging/IResultLogger.cs, src/FluentResults/Results/ResultBase.cs
Hi,
This is something that I've been using for some time as extensions methods, thought would be nice to contribute it back.
This PR adds two new methods for logging:
```csharp
result.LogIfSuccess();
result.LogIfFailed();
```
I know we can achieve that directly in the `IResultLogger` implementation, but I thought will be nice to have some easier shortcuts.
And a new property for .Log() named `content`. This way we can pass additional information directly to the logging methods, without messing with metadatas.
```csharp
var result2 = Result.Fail("Operation failed")
.Log<MyLoggerContext>("More info about the result");
```
Hope that would help someone, as it helped me!
=> Conditional logging and additional log information

src/FluentResults.Test/CheckReasonsTests.cs, src/FluentResults/Factories/ResultHelper.cs
HasException now check exception when they are added to the root of the error like so :
var result = Result.Fail(new ExceptionalError(new ArgumentException("test")));
=> Root exception are now detected in the hasexception function

README.md, src/FluentResults.Test/CheckReasonsTests.cs, src/FluentResults/Reasons/Error.cs
Hi,
Is there a reason why `CausedBy` only allows passing `Error` and not `IError`?
```csharp
var result1 = Result.Fail("Some error");
var result2 = Result.Fail(new Error("Another error").CausedBy(result1.Errors));
```
=> CausedBy IError

src/FluentResults.Test/Playground.cs, src/FluentResults.Test/ResultWithValueTests.cs, src/FluentResults.Test/ResultWithoutValueTests.cs, src/FluentResults/Results/Result.cs, src/FluentResults/Results/ResultBase.cs
Hello,
Currently, when you have a method that returns Result<TValue> you always need to check isSuccess with `result.IsSuccess` its all ok although
add some Deconstruction method can make it more simple 
var (isSuccess, isFailure, value) = Result.Ok(100);
var (isSuccess, value) = Result.Ok(100);
var (isSuccess, value, errors) = Result.Success(100);
=> add Deconstruct Operators to Result and ResultBase

README.md, src/FluentResults.Test/ResultWithoutValueTests.cs, src/FluentResults/Factories/Results.cs
- Implemented lazy error evaluation for `Result.OkIf` and `Result.FailIf` methods (including unit tests).
- Added short description of the feature in the README.
Fixes #141
=> Lazy error evaluation

README.md, src/FluentResults.Test/Playground.cs, src/FluentResults.Test/ResultWithValueTests.cs, src/FluentResults.Test/ResultWithoutValueTests.cs, src/FluentResults/Extensions/ResultExtensions.cs, src/FluentResults/Results/Result.cs
Related to the issues #140 and #108.
This will allow Kleiski compositions (`Result<A>, A -> Result<B>, B -> Result<C>,...`), eliminating the need of using statements to compose the results manually.
=> feat: add .Bind operator to map results into a flattened Result

src/FluentResults.Test/ErrorTests.cs, src/FluentResults/Results/Result.cs
My first PR for implicit conversion from Errors to fail result wasn't working for Result of T.
I was pretty sure the implicit conversion could be done twice. Error --> Result --> Result of T   but it doesn't.
=> Implicit operators for failed Result<T>

src/FluentResults.Test/ResultWithValueTests.cs, src/FluentResults/Results/Result.cs
Allows casting from `Result<T>` to `Result<object>` without packing the value twice.
Resolves #165
=> Fixed `Result<TValue>` to `Result<object>` casting

src/FluentResults.Extensions.FluentAssertions.Test/ValueResultTests/HaveValueTests.cs, src/FluentResults.Extensions.FluentAssertions/Assertions/AssertionOperators.cs
Fixes #172 
As `==` and `.Equals()` can bring some different results depending the code written and/or overrides, I added one extra null comparison step before the current checking.
=> Fixes HaveValue method when type is a class

src/FluentResults.Extensions.FluentAssertions/Assertions/ReasonAssertions.cs
Fix the HaveMetadata equality comparer; now it will compare metadata values using the Equals comparer, as it is usually used to compare by value rather than by reference.
=> Fixed equality comparer inside ReasonAssertions.HaveMetadata().

README.md, src/FluentResults/FluentResults.csproj
After adding the README.md file to the package, the repository's README file can now be viewed at nuget.org.
Resolves #203
=> Added README.md to nuget package to be presented on nuget.org

README.md, src/FluentResults.Test/ResultWithValueTests.cs, src/FluentResults.Test/ResultWithoutValueTests.cs, src/FluentResults/Factories/Results.cs
Adds new methods of Try that allow you to return a new result object
Fixes #166 
Prior to this, you would always get a `Result.Ok` as long as your action did not throw an exception.  This will allow you to further control the flow of your application
=> Add Try with result return

src/FluentResults/Extensions/EnumerableExtensions.cs, src/FluentResults/Extensions/ObjectExtensions.cs, src/FluentResults/Extensions/ResultExtensions.cs, src/FluentResults/Logging/DefaultLogger.cs, src/FluentResults/Logging/IResultLogger.cs, src/FluentResults/Reasons/Error.cs, src/FluentResults/Reasons/ExceptionalError.cs, src/FluentResults/Reasons/IError.cs, src/FluentResults/Reasons/IExceptionalError.cs, src/FluentResults/Reasons/IReason.cs, src/FluentResults/Reasons/ISuccess.cs, src/FluentResults/Reasons/ReasonExtensions.cs, src/FluentResults/Reasons/ReasonStringBuilder.cs, src/FluentResults/Reasons/Success.cs, src/FluentResults/Results/Result.cs, src/FluentResults/Results/ResultBase.cs, src/FluentResults/Settings/ResultSettings.cs, src/FluentResults/Settings/ResultSettingsBuilder.cs
Adds missing XML documentation comments to classes in current `master` branch.  No more warnings for this are emitted at build time.
Closes #136
=> 136 add xml documentation

README.md, src/FluentResults.Test/ResultWithoutValueTests.cs, src/FluentResults/Factories/Results.cs
Adds methods to `FailIf` that will accept a collection of `Error` objects.
Closes #189
=> Add FailIf methods accepting a collection of errors

README.md, src/FluentResults.Test/MergeTests.cs, src/FluentResults/Factories/ResultHelper.cs, src/FluentResults/Factories/Results.cs
Adds a `MergeFlat` method that will take in collections of TValue in your result set and return them as a single flattened `IEnumerable<TValue>`
Unfortunately, due to how C# infers type parameters for encapsulating types, you will need to specify the `TValue` and `TArray` types where `TArray : IEnumerable<TValue>`
```csharp
var result1 = Result.Ok(new string[] { "A", "B" });
var result2 = Result.Ok(new string[] { "C", "D" });
var result3 = Result.Ok(new string[] { "E", "F" });
// Will contain ["A", "B", "C", "D", "E", "F"]
var mergedResult = Result.MergeFlat<string, string[]>(result1, result2, result3);
```
Closes #182
=> 182 Add enumerable support for Merge

README.md, src/FluentResults.Test/ResultWithValueTests.cs, src/FluentResults/Results/Result.cs, src/FluentResults/Results/ResultBase.cs
Currently all deconstructors return a pair `bool isSuccess`/`bool isFailed`, which is slightly redundant (IMO only one would be enough, and if we are just interested in a single bool result we can just get the prop instead of using a desconstructor).
It becomes even more redundant in `Result<TValue>` since in that case we're also (we should be!) returning `TValue value` and possibly `List<IError> errors` - success/failure can just be infered from those values (if they are null) instead of having 4 different methods for testing the same thing.
Previously I've been just discarding the redundant variables: `var (_, _, result, errors) = MyServiceCall()`,  
but I thought that this cleaner/concise syntax could benefit everyone - so the 2-tuple deconstruct would just return us `TValue value` and …
=> ResultOrErrors deconstruct

src/FluentResults.Extensions.FluentAssertions/FluentResults.Extensions.FluentAssertions.csproj, src/FluentResults.Test/FluentResults.Test.csproj
FluentAssertions v8 is now paid for commercial use, package manager should prevent any updates so that FluentResults could be used commercially.
Next phase should probably be passing all dependencies to [Shouldly](https://github.com/shouldly/shouldly) ,
which is now sponsored by FluentAssertions old sponsors.
Closes #231
=> Pin FluentAssertions dependency to prevent future updates
